In [1]:
!pip install transformers --quiet
!pip install git+https://github.com/abheesht17/keras-nlp.git@gpt2-presets tensorflow tensorflow-text --upgrade --quiet

     |████████████████████████████████| 5.5 MB 40.9 MB/s 
     |████████████████████████████████| 7.6 MB 65.3 MB/s 
     |████████████████████████████████| 163 kB 74.0 MB/s 
     |████████████████████████████████| 578.0 MB 17 kB/s 
     |████████████████████████████████| 5.9 MB 56.8 MB/s 
     |████████████████████████████████| 438 kB 71.3 MB/s 
     |████████████████████████████████| 5.9 MB 60.7 MB/s 
     |████████████████████████████████| 1.7 MB 60.3 MB/s 


In [2]:
import json
import os

import keras_nlp
import numpy as np

import tensorflow as tf
from tensorflow import keras

import torch

from transformers import AutoTokenizer, AutoModel

tf.__version__

'2.10.0'

In [3]:
# Variables.

# Should be one of 124M, 355M, 774M, 1558M.
NUM_PARAMS = "355M"

In [4]:
# Let's get the official OpenAI GPT-2 ckpt.

!wget https://raw.githubusercontent.com/openai/gpt-2/master/download_model.py
!python3 download_model.py $NUM_PARAMS

--2022-11-13 09:13:20--  https://raw.githubusercontent.com/openai/gpt-2/master/download_model.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1075 (1.0K) [text/plain]
Saving to: ‘download_model.py’

download_model.py   100%[===================>]   1.05K  --.-KB/s    in 0s      

2022-11-13 09:13:20 (43.1 MB/s) - ‘download_model.py’ saved [1075/1075]

Fetching checkpoint: 1.00kit [00:00, 729kit/s]                                                      
Fetching encoder.json: 1.04Mit [00:01, 547kit/s]                                                    
Fetching hparams.json: 1.00kit [00:00, 1.00Mit/s]                                                   
Fetching model.ckpt.data-00000-of-00001: 1.42Git [05:04, 4.66Mit/s]                                 
Fetching

In [5]:
# GPT-2 paths.
extract_dir = f"/content/models/{NUM_PARAMS}"
merges_path = os.path.join(extract_dir, "vocab.bpe")
vocab_path = os.path.join(extract_dir, "encoder.json")
checkpoint_path = os.path.join(extract_dir, "model.ckpt")
config_path = os.path.join(extract_dir, "hparams.json")

In [6]:
# n_vocab, n_ctx, n_embd, n_head, n_layer
with open(config_path, "r") as f:
    cfg = json.load(f)

cfg

{'n_vocab': 50257, 'n_ctx': 1024, 'n_embd': 1024, 'n_head': 16, 'n_layer': 24}

In [7]:
vars = tf.train.list_variables(checkpoint_path)
weights = {}
for name, shape in vars:
    print(name, shape)
    weight = tf.train.load_variable(checkpoint_path, name)
    weights[name] = weight

model/h0/attn/c_attn/b [3072]
model/h0/attn/c_attn/w [1, 1024, 3072]
model/h0/attn/c_proj/b [1024]
model/h0/attn/c_proj/w [1, 1024, 1024]
model/h0/ln_1/b [1024]
model/h0/ln_1/g [1024]
model/h0/ln_2/b [1024]
model/h0/ln_2/g [1024]
model/h0/mlp/c_fc/b [4096]
model/h0/mlp/c_fc/w [1, 1024, 4096]
model/h0/mlp/c_proj/b [1024]
model/h0/mlp/c_proj/w [1, 4096, 1024]
model/h1/attn/c_attn/b [3072]
model/h1/attn/c_attn/w [1, 1024, 3072]
model/h1/attn/c_proj/b [1024]
model/h1/attn/c_proj/w [1, 1024, 1024]
model/h1/ln_1/b [1024]
model/h1/ln_1/g [1024]
model/h1/ln_2/b [1024]
model/h1/ln_2/g [1024]
model/h1/mlp/c_fc/b [4096]
model/h1/mlp/c_fc/w [1, 1024, 4096]
model/h1/mlp/c_proj/b [1024]
model/h1/mlp/c_proj/w [1, 4096, 1024]
model/h10/attn/c_attn/b [3072]
model/h10/attn/c_attn/w [1, 1024, 3072]
model/h10/attn/c_proj/b [1024]
model/h10/attn/c_proj/w [1, 1024, 1024]
model/h10/ln_1/b [1024]
model/h10/ln_1/g [1024]
model/h10/ln_2/b [1024]
model/h10/ln_2/g [1024]
model/h10/mlp/c_fc/b [4096]
model/h10/mlp/

In [8]:
model = keras_nlp.models.GPT2.from_preset(
    "gpt2_medium",
    load_weights=False,
)

In [9]:
model.summary()

Model: "backbone"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 token_ids (InputLayer)         [(None, None)]       0           []                               
                                                                                                  
 token_embedding (Embedding)    (None, None, 1024)   51463168    ['token_ids[0][0]']              
                                                                                                  
 position_embedding (PositionEm  (None, None, 1024)  1048576     ['token_embedding[0][0]']        
 bedding)                                                                                         
                                                                                                  
 add (Add)                      (None, None, 1024)   0           ['token_embedding[0][0]', 

In [10]:
model.get_layer("token_embedding").embeddings.assign(
    weights["model/wte"]
)
model.get_layer("position_embedding").position_embeddings.assign(
    weights["model/wpe"]
)

range_1 = (0, cfg["n_embd"])
range_2 = (cfg["n_embd"], 2 * cfg["n_embd"]) 
range_3 = (2 * cfg["n_embd"], 3 * cfg["n_embd"])


for i in range(model.num_layers):
    model.get_layer(f"transformer_layer_{i}")._self_attention_layer._query_dense.kernel.assign(
        weights[f"model/h{i}/attn/c_attn/w"][0, :, range_1[0]: range_1[1]].reshape((cfg["n_embd"], cfg["n_head"], -1))
    )
    model.get_layer(f"transformer_layer_{i}")._self_attention_layer._query_dense.bias.assign(
        weights[f"model/h{i}/attn/c_attn/b"][range_1[0]: range_1[1]].reshape((cfg["n_head"], -1))
    )
    model.get_layer(f"transformer_layer_{i}")._self_attention_layer._key_dense.kernel.assign(
        weights[f"model/h{i}/attn/c_attn/w"][0, :, range_2[0]: range_2[1]].reshape((cfg["n_embd"], cfg["n_head"], -1))
    )
    model.get_layer(f"transformer_layer_{i}")._self_attention_layer._key_dense.bias.assign(
        weights[f"model/h{i}/attn/c_attn/b"][range_2[0]: range_2[1]].reshape((cfg["n_head"], -1))
    )
    model.get_layer(f"transformer_layer_{i}")._self_attention_layer._value_dense.kernel.assign(
        weights[f"model/h{i}/attn/c_attn/w"][0, :, range_3[0]: range_3[1]].reshape((cfg["n_embd"], cfg["n_head"], -1))
    )
    model.get_layer(f"transformer_layer_{i}")._self_attention_layer._value_dense.bias.assign(
        weights[f"model/h{i}/attn/c_attn/b"][range_3[0]: range_3[1]].reshape((cfg["n_head"], -1))
    )


    model.get_layer(f"transformer_layer_{i}")._self_attention_layer._output_dense.kernel.assign(
        weights[f"model/h{i}/attn/c_proj/w"][0].reshape((cfg["n_head"], -1, cfg["n_embd"]))
    )
    model.get_layer(f"transformer_layer_{i}")._self_attention_layer._output_dense.bias.assign(
        weights[f"model/h{i}/attn/c_proj/b"]
    )


    model.get_layer(f"transformer_layer_{i}")._self_attention_layernorm.gamma.assign(
        weights[f"model/h{i}/ln_1/g"]
    )
    model.get_layer(f"transformer_layer_{i}")._self_attention_layernorm.beta.assign(
        weights[f"model/h{i}/ln_1/b"]
    )


    model.get_layer(f"transformer_layer_{i}")._feedforward_intermediate_dense.kernel.assign(
        weights[f"model/h{i}/mlp/c_fc/w"][0]
    )
    model.get_layer(f"transformer_layer_{i}")._feedforward_intermediate_dense.bias.assign(
        weights[f"model/h{i}/mlp/c_fc/b"]
    )


    model.get_layer(f"transformer_layer_{i}")._feedforward_output_dense.kernel.assign(
        weights[f"model/h{i}/mlp/c_proj/w"][0]
    )
    model.get_layer(f"transformer_layer_{i}")._feedforward_output_dense.bias.assign(
        weights[f"model/h{i}/mlp/c_proj/b"]
    )


    model.get_layer(f"transformer_layer_{i}")._feedforward_layernorm.gamma.assign(
        weights[f"model/h{i}/ln_2/g"]
    )
    model.get_layer(f"transformer_layer_{i}")._feedforward_layernorm.beta.assign(
        weights[f"model/h{i}/ln_2/b"]
    )


model.get_layer("layer_norm").gamma.assign(
    weights[f"model/ln_f/g"]
)

model.get_layer("layer_norm").beta.assign(
    weights[f"model/ln_f/b"]
)
pass

In [11]:
# Define KerasNLP components.

bpe_tokenizer = keras_nlp.tokenizers.BytePairTokenizer(
    vocabulary=vocab_path,
    merges=merges_path,
    # sequence_length=cfg["n_ctx"]
)

# Define HF components.

hf_tokenizer = AutoTokenizer.from_pretrained("gpt2-medium")
hf_model = AutoModel.from_pretrained("gpt2-medium")
hf_model.eval()
pass

Downloading:   0%|          | 0.00/718 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/456k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.52G [00:00<?, ?B/s]

In [12]:
# KerasNLP
token_ids = bpe_tokenizer(["the quick brown fox ran, galloped and jumped."])
padding_mask = token_ids != 0

inputs = {
    "token_ids": token_ids.to_tensor(),
    "padding_mask": padding_mask.to_tensor()
}

keras_nlp_output = model.predict(inputs)

# HF
hf_inputs = hf_tokenizer(["the quick brown fox ran, galloped and jumped."], return_tensors="pt")
hf_output = hf_model(**hf_inputs).last_hidden_state

1/1 [==============================] - 8s 8s/step


In [13]:
keras_nlp_output[0, 0, :10], hf_output[0, 0, :10]

(array([-0.18603998, -0.29847348, -0.36645514,  0.786773  , -0.15711385,
        -0.18149738, -0.00163372, -0.48359686, -0.1866399 , -1.6125616 ],
       dtype=float32),
 tensor([-0.1860, -0.2985, -0.3665,  0.7868, -0.1571, -0.1815, -0.0016, -0.4836,
         -0.1866, -1.6126], grad_fn=<SliceBackward0>))

In [14]:
np.mean(keras_nlp_output - hf_output.detach().numpy())

3.0315807e-08

In [15]:
# Save GPT2 checkpoint.
model.save_weights("gpt2_medium.h5")

In [16]:
model2 = keras_nlp.models.GPT2.from_preset(
    "gpt2_medium",
    load_weights=False,
)
model2.load_weights("gpt2_medium.h5")

In [17]:
token_ids = bpe_tokenizer(["the quick brown fox ran, galloped and jumped."])
padding_mask = token_ids != 0

inputs = {
    "token_ids": token_ids.to_tensor(),
    "padding_mask": padding_mask.to_tensor()
}

keras_nlp_output2 = model2.predict(inputs)

1/1 [==============================] - 4s 4s/step


In [18]:
tf.reduce_mean(keras_nlp_output - keras_nlp_output2)

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [ ]:
!md5sum gpt2_medium.h5

580ff9b79c04fc90e6d6f47e975c5afe  gpt2_medium.h5


In [19]:
# Check uploaded model once added to repo
model_cloud = keras_nlp.models.GPT2.from_preset(
    "gpt2_medium",
    load_weights=True
)

1419729400/1419729400 [==============================] - 68s 0us/step


In [20]:
# Same output from cloud model
keras_nlp_output_cloud = model_cloud.predict(inputs)
tf.reduce_mean(keras_nlp_output - keras_nlp_output_cloud)

1/1 [==============================] - 4s 4s/step


<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [21]:
keras_nlp_output_cloud[0, 0, :10]

array([-0.18603998, -0.29847348, -0.36645514,  0.786773  , -0.15711385,
       -0.18149738, -0.00163372, -0.48359686, -0.1866399 , -1.6125616 ],
      dtype=float32)